install pyyaml via apt
pyiron/actions pull request #134
Opened 2024-10-15 15:21 UTC by mbruns91

See title. Somehow, the runner-os complains when trying to use `pip install pyyaml`. So I replaced this by `apt install python3-yaml`. See also [here](https://github.com/pyiron/uniton/pull/11#issuecomment-2414207685)

2024-10-15 16:39 UTC, liamhuber requested changes
Rather not; per [this comment](https://github.com/pyiron/uniton/pull/11#issuecomment-2414502245) this would break the action for windows, and the problem seems to be an upstream issue -- better that users avoid specifying the problematic runner. I recommend to close this PR.

2024-10-15 17:35 UTC, mbruns91 commented
I'm totally on your page to not break this action for non-ubuntu runners. But I think it's a bit unsatisfactory to implicitly pin the upper bound of the OS version.

We could, for example, ether
- have a look how the `pipx` command can be used on windows and MacOS runner-images; this is an alterative way to install pip packages without messing with system-python by using a `venv`.
- install `pyyaml` (and other pip-iunstalled packages) - if possible - via the respective package manager: APT (`apt`) for ubuntu, homebrew (`brew`) for MacOS and Chocolatey (`choco`) for windows.
(have a look [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners))

I'm on mobile right now and I don't think I'll come back to my PC before tomorrow morning. But I'd be happy to work on this, if you agree that this should be implemented in a more flexible way.

2024-10-15 17:47 UTC, liamhuber commented
> Maybe this issue will also be solved by the github devs over https://github.com/actions/runner-images/issues/10781.
> I changed this PR to draft for now.

Yes, this is the crux of my argument -- it's not our fault, and if we wait a bit it will go away.

> I'm totally on your page to not break this action for non-ubuntu runners. But I think it's a bit unsatisfactory to implicitly pin the upper bound of the OS version.

Instead of "fixing" it in the action here, we could alternatively make a (temporary) fix in the reusable workflow itself where we explicitly change the default runner from "ubuntu-latest" to a pinned older ubuntu runner.

2024-10-16 09:35 UTC, mbruns91 commented
When seeing their discussion, I'm not so sure they will fix it soon.
Alternatively, to avoid work downstream now and also when the issue might get fixed, we could use `ubuntu-22.04` as default. Otherwise some of our workflows fail by default and also it's super easy to revert this to `ubuntu-latest` if required.

2024-10-16 10:17 UTC, mbruns91 commented
Another solution would be to use
```
pip install <package> --break-system-packages
```
.
While this is generally considered bad practice, I think it's okay for runners, as they are killed quickly anyway.

2024-10-16 13:33 UTC, liamhuber commented
My top preference would be to leverage the existing `runner` kwarg downstream, I can also handle updating the default.

2025-06-27 03:32 UTC, closed without merging